### ISSUE TITLE
Improve footer

### ISSUE THREAD

**Issue by AyushSarode** [AyushSarode/LearningApp#11]

**Comment by Lo-rraine** [comment]
Hi There,

I Love how the website has been designed : )

I would love to work on the footer, may you assign this issue to me

**Comment by AyushSarode** [comment]
> Thank you!!!
> 

Are you working on it?

**Comment by Lo-rraine** [comment]
Yes I'll be making a PR soon

**Comment by AyushSarode** [comment]
Are you working on nav hover issue?

**Comment by Lo-rraine** [comment]
> Are you working on nav hover issue?

Hi there can you assign the issue to me :)

**Comment by AyushSarode** [comment]
> > Are you working on nav hover issue?
> 
> Hi there can you assign the issue to me :)

Create issue for that, I'll assign you
