### ISSUE TITLE
Improve readme.md

### ISSUE THREAD

**Issue by AyushSarode** [AyushSarode/LearningApp#13]

**Comment by Vani177** [comment]
hey, i wanna work on this issue, can you please assign it to me?

**Comment by AyushSarode** [comment]
> hey, i wanna work on this issue, can you please assign it to me?

Go ahead!

**Comment by Vani177** [comment]
> > hey, i wanna work on this issue, can you please assign it to me?
> 
> Go ahead!

yup, thanks!

**Comment by AyushSarode** [comment]
> Can I contribute in it too sir?

Already assigned! If you want to contribute in this repo, create genuine issue.
