### ISSUE TITLE
Add an Anchor Link to Jump to a Specific Section of a Page

### ISSUE THREAD

**Issue by AyushSarode** [AyushSarode/LearningApp#2]

**Comment by tokyo3001** [comment]
@AyushSarode Can you assign me this issue?

**Comment by Manujdixit** [comment]
@AyushSarode ,I would like to work on this issue. Could you please assign me this issue.

**Comment by AyushSarode** [comment]
> @AyushSarode ,I would like to work on this issue. Could you please assign me this issue.
Also give a star to this repo
