### ISSUE TITLE
Make website mobile responsive

### ISSUE THREAD

**Issue by AyushSarode** [AyushSarode/LearningApp#20]

**Comment by Aman0786-git** [comment]
can you assign it to me

**Comment by AyushSarode** [comment]
> can you assign it to me



> can you assign it to me

Go ahead!
When will you finish the work?

**Comment by AyushSarode** [comment]
> assign it to me pls

You can create genuine issue and work on it if it's really useful to me

**Comment by Aman0786-git** [comment]
> Go ahead! When will you finish the work?

I will be travelling tomorrow to my home so I will do it after reaching there

**Comment by AyushSarode** [comment]
> can you assign it to me



> > Go ahead! When will you finish the work?
> 
> I will be travelling tomorrow to my home so I will do it after reaching there

Sure

**Comment by AyushSarode** [comment]
make sure you do like this repo

**Comment by AyushSarode** [comment]
> > Go ahead! When will you finish the work?
> 
> I will be travelling tomorrow to my home so I will do it after reaching there

Are you working on it?

**Comment by Aman0786-git** [comment]
> Are you working on it?

yup I am working on it today due to our festival I was not able to complete it

**Comment by AyushSarode** [comment]
> > Are you working on it?
> 
> yup I am working on it today due to our festival I was not able to complete it

Can You complete it today?

**Comment by dissyulina** [comment]
Hi, would love to work on it if it's still open.

**Comment by AyushSarode** [comment]
> Hi, would love to work on it if it's still open.

Go ahead!

**Comment by AyushSarode** [comment]
> Hi, would love to work on it if it's still open.

When will you finish it?

**Comment by dissyulina** [comment]
> When will you finish it?

It's my first time contributing and making a PR, so it will take me a few hours :)

**Comment by AyushSarode** [comment]
> > When will you finish it?
> 
> It's my first time contributing and making a PR, so it will take me a few hours :)

Sure! Take your time.

**Comment by AyushSarode** [comment]
> > When will you finish it?
> 
> It's my first time contributing and making a PR, so it will take me a few hours :)

Kindly give a star to this repo

**Comment by Aman0786-git** [comment]
> > > Are you working on it?
> > 
> > 
> > yup I am working on it today due to our festival I was not able to complete it
> 
> Can You complete it today?

Will try best
