### ISSUE TITLE
Change menu button position

### ISSUE THREAD

**Issue by AyushSarode** [AyushSarode/LearningApp#21]
As you see this the menu button is obstructing text. I hope you'll solve it.
![Screenshot 2022-10-08 014924](https://user-images.githubusercontent.com/72145248/194646432-36038e69-f505-4979-8edb-da58bda1281c.png)

**Comment by jha-om** [comment]
can i work on this issue?

**Comment by jha-om** [comment]
may u assign this issue to me?

**Comment by jha-om** [comment]
tomorrow.

**Comment by AyushSarode** [comment]
9 

> tomorrow.

8 oct or 9 oct ?

**Comment by jha-om** [comment]
today itself!
I thought today is 7 oct

**Comment by AyushSarode** [comment]
> today itself! I thought today is 7 oct

yeah that's my I asked about it.
