### ISSUE TITLE
Improve responsiveness

### ISSUE THREAD

**Issue by AyushSarode** [AyushSarode/LearningApp#26]

**Comment by deoliaman00** [comment]
I would like to work on this issue. Can you assign it to me?

**Comment by AyushSarode** [comment]
Sure
Go ahead!

**Comment by rashmirekhakumari** [comment]
Can you assign it to me?

**Comment by AyushSarode** [comment]
> Can you assign it to me?

Sure, Go ahead

**Comment by devhabeeblateef** [comment]
Can you assign it to me?

**Comment by AyushSarode** [comment]
Sure

**Comment by Aniketmishra0** [comment]
Hello Sir,
Can You assign this issue to me?
