### ISSUE TITLE
Title Missing from the web Page

### ISSUE THREAD

**Issue by itzwow** [AyushSarode/LearningApp#27]
![is1](https://user-images.githubusercontent.com/84179065/194775266-9aaa2351-c9f9-43b3-a174-43a0445374ce.JPG)

The title is missing from the index.html page

I would like to work on the issue

**Comment by AyushSarode** [comment]
Sure. Go ahead but if I won't like it, I will close your PR.
All the best!

**Comment by AyushSarode** [comment]
> Sure. Go ahead but if I won't like it, I will close your PR. 
Also give a star to this repo.
All the best!

**Comment by itzwow** [comment]
Should I give something of my own or will you suggest ?

**Comment by AyushSarode** [comment]
> Should I give something of my own or will you suggest ?

Try something by your own but webpage should look good to me after completion
