### ISSUE TITLE
Adding dark mode

### ISSUE THREAD

**Issue by AD1TYA03** [AyushSarode/LearningApp#34]
Light mode doesn't seems to be pleasing
 
 **Changes Needed**
1. Adding Dark-mode button. (so that webpage is both light mode and dark mode)
2. logo fades or hidden in bright mode , need some changes
3. Fonts need to be improved

**Comment by AD1TYA03** [comment]
Add a label of hactoberfest and assign it to me , I will get this done.

**Comment by AyushSarode** [comment]
Sure, Go ahead!

**Comment by AD1TYA03** [comment]
@AyushSarode If you don't mind can I split this in 2 or 3 PRs , as I have to complete my Hactoberfest PR tasks as well 😅

**Comment by AyushSarode** [comment]
> @AyushSarode If you don't mind can I split this in 2 or 3 PRs , as I have to complete my Hactoberfest PR tasks as well 😅

Yes, also this is my another repo, you can contribute in this too, add dark mode here.
https://github.com/AyushSarode/Social-media-buttons.github.io

**Comment by AyushSarode** [comment]
> @AyushSarode If you don't mind can I split this in 2 or 3 PRs , as I have to complete my Hactoberfest PR tasks as well 😅

And also can you tell me how did you add PRO tag in your profile, how much did you give to github? or is it free?

**Comment by AD1TYA03** [comment]
> > @AyushSarode If you don't mind can I split this in 2 or 3 PRs , as I have to complete my Hactoberfest PR tasks as well 😅
> 
> And also can you tell me how did you add PRO tag in your profile, how much did you give to github? or is it free?

It's free you just need to be a university student , visit https://education.github.com/ and register yourself for student developer pack

**Comment by AyushSarode** [comment]
> > > @AyushSarode If you don't mind can I split this in 2 or 3 PRs , as I have to complete my Hactoberfest PR tasks as well 😅
> > 
> > 
> > And also can you tell me how did you add PRO tag in your profile, how much did you give to github? or is it free?
> 
> It's free you just need to be a university student , visit https://education.github.com/ and register yourself for student developer pack

I'm in 12th grade!

**Comment by AD1TYA03** [comment]
@AyushSarode Hey could you please add a new branch named dark-mode so I can generate PR into that , without affecting the main branch




Initial commits are ready :-
<img width="1394" alt="Screenshot 2022-10-12 at 4 05 40 PM" src="https://user-images.githubusercontent.com/90272291/195321701-ada38956-4c37-4855-a82f-6e91a5fefdb0.png">
<img width="1440" alt="Screenshot 2022-10-12 at 4 05 53 PM" src="https://user-images.githubusercontent.com/90272291/195321729-4011e0f8-b642-4b81-b8cc-e49a8e5372de.png">
<img width="1438" alt="Screenshot 2022-10-12 at 4 06 12 PM" src="https://user-images.githubusercontent.com/90272291/195321754-c4cfb4c7-fbfc-47e0-813b-3bed2c615599.png">

**Comment by AyushSarode** [comment]
> @AyushSarode Hey could you please add a new branch named dark-mode so I can generate PR into that , without affecting the main branch
> 
> Initial commits are ready :- <img alt="Screenshot 2022-10-12 at 4 05 40 PM" width="1394" src="https://user-images.githubusercontent.com/90272291/195321701-ada38956-4c37-4855-a82f-6e91a5fefdb0.png"> <img alt="Screenshot 2022-10-12 at 4 05 53 PM" width="1440" src="https://user-images.githubusercontent.com/90272291/195321729-4011e0f8-b642-4b81-b8cc-e49a8e5372de.png"> <img alt="Screenshot 2022-10-12 at 4 06 12 PM" width="1438" src="https://user-images.githubusercontent.com/90272291/195321754-c4cfb4c7-fbfc-47e0-813b-3bed2c615599.png">

Sure, looks amazing

**Comment by AyushSarode** [comment]
> > @AyushSarode Hey could you please add a new branch named dark-mode so I can generate PR into that , without affecting the main branch
> > Initial commits are ready :- <img alt="Screenshot 2022-10-12 at 4 05 40 PM" width="1394" src="https://user-images.githubusercontent.com/90272291/195321701-ada38956-4c37-4855-a82f-6e91a5fefdb0.png"> <img alt="Screenshot 2022-10-12 at 4 05 53 PM" width="1440" src="https://user-images.githubusercontent.com/90272291/195321729-4011e0f8-b642-4b81-b8cc-e49a8e5372de.png"> <img alt="Screenshot 2022-10-12 at 4 06 12 PM" width="1438" src="https://user-images.githubusercontent.com/90272291/195321754-c4cfb4c7-fbfc-47e0-813b-3bed2c615599.png">
> 
> I created branch for darkmode, btw it looks amazing!

**Comment by AD1TYA03** [comment]
@AyushSarode thanks

**Comment by Aniketmishra0** [comment]
Hello Sir,
Can You assign this issue to me?
