### ISSUE TITLE
Add Searchbar

### ISSUE THREAD

**Issue by devhabeeblateef** [AyushSarode/LearningApp#38]
Hello! I will love to add a search bar at the top, for easier navigation.
Can you assign this to me? I will love to use the pull request for #Hacktoberfest

**Comment by AyushSarode** [comment]
> Hello! I will love to add a search bar at the top, for easier navigation.
> Can you assign this to me? I will love to use the pull request for #Hacktoberfest

Sure! 
Make sure to give a preview before creating PR.

**Comment by devhabeeblateef** [comment]
I've added the SearchBar, here is the preview in Desktop, Tablet and Mobile view. 

Please review.
![SearchBar(Desktop view)](https://user-images.githubusercontent.com/77229868/195855962-27c72d48-63fb-4ff2-b0a8-de2d39f5b5df.png)
![SearchBar(MobileView)](https://user-images.githubusercontent.com/77229868/195856030-5581a604-47f7-4fce-8c71-ce4bd8b556c7.png)
![Searchbar(tablet view)](https://user-images.githubusercontent.com/77229868/195856042-c8635966-c4ca-4953-b4c0-22cc1d4c5d3f.png)

**Comment by Aniketmishra0** [comment]
Can you please add the Hacktoberfest label to this issue

**Comment by AyushSarode** [comment]
> Can you please add the Hacktoberfest label to this issue

@devhabeeblateef is already assign.
Sorry @Aniketmishra0

**Comment by devhabeeblateef** [comment]
Ok, I will adjust

**Comment by devhabeeblateef** [comment]
Here are the changes.
1. Reduced Search bar size
2. Adjusted position of search bar

Please review.
![DesktopView](https://user-images.githubusercontent.com/77229868/195895138-e02649fd-23c7-4f79-820e-df0b5a226c54.png)
![MobileView](https://user-images.githubusercontent.com/77229868/195895211-8ad40a42-6906-4d52-9fd3-fdc09cfaacc2.png)
![TabletView](https://user-images.githubusercontent.com/77229868/195895229-c67550fa-c571-48b1-8620-69becbc50c0c.png)

**Comment by AyushSarode** [comment]
Move it to the equal level of menu bar

**Comment by AyushSarode** [comment]
that's it!

**Comment by devhabeeblateef** [comment]
Here are the changes

Please review
![DesktopView](https://user-images.githubusercontent.com/77229868/195942068-585d2416-73aa-4cc8-a683-ded8ab267eeb.png)
![MobileView](https://user-images.githubusercontent.com/77229868/195942094-560567c2-12d1-4bc2-910e-ca9a40d69375.png)
![TabletView](https://user-images.githubusercontent.com/77229868/195942111-411e7420-32f4-4d25-9434-7890aae05372.png)

**Comment by AyushSarode** [comment]
> Here are the changes
> 
> Please review
> ![DesktopView](https://user-images.githubusercontent.com/77229868/195942068-585d2416-73aa-4cc8-a683-ded8ab267eeb.png)
> ![MobileView](https://user-images.githubusercontent.com/77229868/195942094-560567c2-12d1-4bc2-910e-ca9a40d69375.png)
> ![TabletView](https://user-images.githubusercontent.com/77229868/195942111-411e7420-32f4-4d25-9434-7890aae05372.png)
> 

Amazing! 
GO FOR PR!
