### ISSUE TITLE
Create a page with Courses Section

### ISSUE THREAD

**Issue by Lo-rraine** [AyushSarode/LearningApp#39]
Hi @AyushSarode 
I see that the see all courses button is not linked to a page
I would like to create a Courses page that will be navigated to, once you press the View all Courses button
![image](https://user-images.githubusercontent.com/65586580/195784519-b88d0de6-77aa-4a3e-b34d-b3b063211403.png)

**Comment by AyushSarode** [comment]
> Hi @AyushSarode 
> I see that the see all courses button is not linked to a page
> I would like to create a Courses page that will be navigated to, once you press the View all Courses button
> ![image](https://user-images.githubusercontent.com/65586580/195784519-b88d0de6-77aa-4a3e-b34d-b3b063211403.png)
> 

Sounds good! 
All the best.

**Comment by Lo-rraine** [comment]
Thanks I'll start working on it

**Comment by Aniketmishra0** [comment]
Hello Sir,
Can You assign this issue to me?
