### ISSUE TITLE
add searchbar

### ISSUE THREAD

**Issue by AyushSarode** [AyushSarode/LearningApp#43]
Add this feature in between where I marked. This feature must have hover and animation
![Capture](https://user-images.githubusercontent.com/72145248/196274168-6e38ad57-c979-451f-a0e6-3421f5159a99.PNG)

**Comment by vaibhv232** [comment]
assign me this issue I will be happy to fix it

**Comment by AyushSarode** [comment]
Sure

**Comment by ankit060801** [comment]
hello sir please assign me this task

**Comment by xuann6** [comment]
hello sir i would like to do this task, thx.

**Comment by SattyamSamania** [comment]
Hey @AyushSarode if the issue is still open, Can I work on this?
