### ISSUE TITLE
Improve the responsiveness of hero section

### ISSUE THREAD

**Issue by thisisamish** [AyushSarode/LearningApp#46]
The website looks weird when viewed on a mobile device. I would love to make it's hero section responsive.

![image](https://user-images.githubusercontent.com/71922206/196434622-507cb38b-caec-4ce0-9d18-4f97f9b6cba6.png)

**Comment by AyushSarode** [comment]
Are you working on it?

**Comment by thisisamish** [comment]
Yeah, sorry I had my exams so got caught up in that but working on this now.

**Comment by AyushSarode** [comment]
> Yeah, sorry I had my exams so got caught up in that but working on this now.

Sure!
Take your time.

**Comment by thisisamish** [comment]
Hey @AyushSarode, I was working on making the hero section responsive but there's no way for me to actually do it without significantly restructuring the HTML *and* CSS. This will essentially mean rewriting the whole section again and I don't think I can do it. So please assign this to someone else.

**Comment by thisisamish** [comment]
Sorry, I closed this issue by mistake.
