### ISSUE TITLE
Redesign the entire website

### ISSUE THREAD

**Issue by zugzwang03** [AyushSarode/LearningApp#49]
The entire website is filled with dummy text. Can I redesign it with appropriate messaging and content.  I want to contribute under hacktoberfest '22.

**Comment by AyushSarode** [comment]
Sure, Go ahead.
Also before creating PR kindly send me Screenshot (preview) here.
All the best!

**Comment by zugzwang03** [comment]
> Sure, Go ahead. Also before creating PR kindly send me Screenshot (preview) here. All the best!

Yeah sure

**Comment by AyushSarode** [comment]
Good work!
Go or PR
