### ISSUE TITLE
Improve Readme.md

### ISSUE THREAD

**Issue by AyushSarode** [AyushSarode/LearningApp#5]

**Comment by Tishachhabra** [comment]
Assign this to me please

**Comment by ashu26jha** [comment]
Hello @AyushSarode can you assign this to me I would  link to contribute.md and also add essence of the project

**Comment by AyushSarode** [comment]
Anyone working on it?

**Comment by AyushSarode** [comment]
> > Anyone working on it?
> 
> Yes sir I am working on it

Give a star to this repo

**Comment by ashu26jha** [comment]
> > > Anyone working on it?
> > 
> > 
> > Yes sir I am working on it
> 
> Give a star to this repo

Stared.

**Comment by AyushSarode** [comment]
> > > > Anyone working on it?
> > > 
> > > 
> > > Yes sir I am working on it
> > 
> > 
> > Give a star to this repo
> 
> Stared.

Thanks!

**Comment by AyushSarode** [comment]
> > Anyone working on it?
> 
> Yes sir I am working on it

Can I get improved readme file today?
