### ISSUE TITLE
Fix the footer

### ISSUE THREAD

**Issue by zugzwang03** [AyushSarode/LearningApp#51]
The footer looks very disorganized. It would be good if it can aligned well and fitted properly.  Can I work on this issue under hacktoberfest '22? 
![Screenshot_20221018-232546_Chrome](https://user-images.githubusercontent.com/95460021/196508036-b63a8fc1-17c1-424e-ac41-c0481324c1a8.jpg)

**Comment by AyushSarode** [comment]
Sure

**Comment by zugzwang03** [comment]
The changes made are below, kindly review them.


https://user-images.githubusercontent.com/95460021/196886662-e8c378bd-b9cd-4302-bb3e-133eca74dc4a.mp4

**Comment by AyushSarode** [comment]
Nice!
Make PR!

**Comment by SattyamSamania** [comment]
Hey @AyushSarode if the issue is still open can I work on this?
