### ISSUE TITLE
Add hovering effect on social media icons

### ISSUE THREAD

**Issue by zugzwang03** [AyushSarode/LearningApp#56]
Will I add some hovering effect on the social media icons in the footer, like some color changes, and scaling.
Can I add this change under hacktoberfest'22?

**Comment by Kritika30032002** [comment]
assign this to me!!

**Comment by zugzwang03** [comment]
The changes are as follows:

https://user-images.githubusercontent.com/95460021/197013193-b8ad4e70-9e47-4a71-ad63-5c731e2b8faf.mp4

**Comment by AyushSarode** [comment]
Go for PR!
