### ISSUE TITLE
Add content in the cards of the "courses" section

### ISSUE THREAD

**Issue by zugzwang03** [AyushSarode/LearningApp#65]
The content present in the cards section of "explore courses" page contains dummy text. I can replace that with appropriate content valid for those sub-topics present in each card. Can I work on this issue under Hacktoberfest'22?

![content](https://user-images.githubusercontent.com/95460021/197107789-3b36fb03-7d4d-42ae-9f12-10a6d99c01ca.png)
![content2](https://user-images.githubusercontent.com/95460021/197107803-cd49513c-ff10-4ecf-a397-b516cc03ce18.png)

**Comment by zugzwang03** [comment]
@AyushSarode

**Comment by AyushSarode** [comment]
Work in it!
