### ISSUE TITLE
Designing the mobile view of the website

### ISSUE THREAD

**Issue by adityabisoyi** [AyushSarode/LearningApp#67]
There are some issues in the text and images in the mobile view. The footer does not look that good in mobile view and the hero image is overlapped by the text.
![image](https://user-images.githubusercontent.com/109476995/197116273-b755133d-6d65-4852-a534-63f3e39d47ed.png)
![image](https://user-images.githubusercontent.com/109476995/197116328-1449b3c3-4553-42b9-aab5-212a4a9192c3.png)

**Comment by adityabisoyi** [comment]
I can solve this issue. Please assign this to me.

**Comment by AyushSarode** [comment]
I need this. 
Go ahead!
