### ISSUE TITLE
Change Sidenav Buttons position

### ISSUE THREAD

**Issue by AyushSarode** [AyushSarode/LearningApp#7]
Buttons should be here -
![Screenshot 2022-10-06 144435](https://user-images.githubusercontent.com/72145248/194275052-43510a7e-b25b-4e2f-bf11-ddd771a2dfa0.png)

**Comment by EnechukwuChibuike** [comment]
Let me work on it.

**Comment by AyushSarode** [comment]
Sure you can both work on it. I'll merge the one which looks good according to me.

**Comment by EnechukwuChibuike** [comment]
![side](https://user-images.githubusercontent.com/60268843/194282028-c207feb3-660c-4512-bc66-30dcc5f3b1a3.png)

Done!

**Comment by RishabhJain0721** [comment]
I have made a pr.Please review it @AyushSarode

**Comment by AyushSarode** [comment]
> ![side](https://user-images.githubusercontent.com/60268843/194282028-c207feb3-660c-4512-bc66-30dcc5f3b1a3.png)
> 
> Done! @AyushSarode

Bring down that home button 
Also no need to put empty space at botton
![194282028-c207feb3-660c-4512-bc66-30dcc5f3b1a3](https://user-images.githubusercontent.com/72145248/194283082-7d67daad-59e5-429c-b1c1-b8265b835750.png)

**Comment by EnechukwuChibuike** [comment]
> > ![side](https://user-images.githubusercontent.com/60268843/194282028-c207feb3-660c-4512-bc66-30dcc5f3b1a3.png)
> > Done! @AyushSarode
> 
> Bring down that home button Also no need to put empty space at bottom ![194282028-c207feb3-660c-4512-bc66-30dcc5f3b1a3](https://user-images.githubusercontent.com/72145248/194283358-b5c018fa-430b-4903-9739-35047226c3f9.png)

Do you mean the "Home" should be under the menu-icon?
