### ISSUE TITLE
Hover effect on buttons

### ISSUE THREAD

**Issue by Amisha0606** [AyushSarode/LearningApp#70]
There are not any hover effects on the buttons of "Start free trial", Read more, view all courses. 
I would like to work on this issue.

**Comment by AyushSarode** [comment]
Go Ahead!

**Comment by ankitkumar0622** [comment]
Hi , can you assign me this task .

**Comment by YashPandey7** [comment]
please assign me this task

**Comment by akshay2501** [comment]
Can you assign me this task.
